# Generated by Django 4.0.5 on 2022-07-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.TextField(blank=True),
        ),
    ]
