# Generated by Django 4.0.5 on 2022-07-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_remove_order_deliveryagent_order_is_cart_and_more'),
        ('CustomUser', '0003_alter_customuser_city_alter_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='MyOrders',
            field=models.ManyToManyField(to='Order.order'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
