# Generated by Django 4.0.5 on 2022-07-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_seller_alter_product_sellers'),
        ('Order', '0002_order_transactionid_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colour')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_seller')),
                ('Varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.varient')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Order.products'),
        ),
    ]
