# Generated by Django 4.0.5 on 2022-07-08 03:46

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0003_products_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryAgent',
        ),
        migrations.AddField(
            model_name='order',
            name='is_cart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 8, 9, 16, 14, 205252)),
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
