# Generated by Django 4.0.5 on 2022-07-08 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_remove_order_deliveryagent_order_is_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 8, 9, 16, 49, 391150)),
        ),
    ]
