# Generated by Django 4.0.5 on 2022-07-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_remove_order_orddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentMode',
        ),
    ]
