# Generated by Django 4.0.5 on 2022-07-08 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_order_customer_order_orddate_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 8, 9, 57, 10, 974084)),
        ),
    ]
