# Generated by Django 4.0.5 on 2022-07-09 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_alter_order_orddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 9, 6, 32, 27, 449691)),
        ),
    ]
