# Generated by Django 4.0.5 on 2022-07-09 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_alter_order_orddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='TransactionId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 9, 9, 33, 39, 862999)),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='Order.products'),
        ),
    ]
