# Generated by Django 4.0.5 on 2022-07-09 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_alter_order_transactionid_alter_order_orddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 9, 16, 22, 41, 65666)),
        ),
    ]
