# Generated by Django 4.0.5 on 2022-07-09 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_product_tags_product_is_root_and_more'),
        ('Order', '0020_alter_order_orddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Varient',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 9, 17, 45, 41, 452036)),
        ),
        migrations.AlterField(
            model_name='products',
            name='Colour',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.colour'),
        ),
    ]
