# Generated by Django 4.0.5 on 2022-07-09 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0021_remove_products_varient_alter_order_orddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 9, 17, 46, 56, 280665)),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='Order.products'),
        ),
    ]
