# Generated by Django 4.0.5 on 2022-07-09 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0022_alter_order_orddate_alter_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Colour',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 9, 17, 47, 40, 39952)),
        ),
    ]
