# Generated by Django 4.0.5 on 2022-07-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0024_remove_order_customer_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
