# Generated by Django 4.0.5 on 2022-07-04 15:01

from django.conf import settings
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_category_colour_varient_product_sellers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('desc', models.TextField()),
                ('Rating', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='Img/default_prduct.jpg', upload_to=products.models.Product_img),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sellers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='Reviews',
            field=models.ManyToManyField(to='products.review'),
        ),
    ]
