# Generated by Django 4.0.5 on 2022-07-04 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_review_alter_product_image_alter_product_sellers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Reviews',
            field=models.ManyToManyField(blank=True, to='products.review'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sellers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
