# Generated by Django 4.0.5 on 2022-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_reviews_alter_product_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
