# Generated by Django 4.0.5 on 2022-07-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_seller_alter_product_sellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Varients',
            field=models.ManyToManyField(blank=True, to='products.varient'),
        ),
    ]
