# Generated by Django 4.0.5 on 2022-07-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Varients',
        ),
        migrations.AddField(
            model_name='product',
            name='Varients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.varient'),
        ),
    ]
