# Generated by Django 4.0.5 on 2022-07-08 11:23

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_offers_bestsellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='Img/default_prduct.jpg', upload_to=products.models.Category_img),
        ),
    ]
