# Generated by Django 4.0.5 on 2022-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_tags',
            field=models.TextField(default=models.TextField(max_length=50)),
        ),
        migrations.AddField(
            model_name='product',
            name='is_root',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='varient_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
