# Generated by Django 4.0.5 on 2022-07-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_product_tags_product_is_root_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_tags',
            field=models.TextField(default=models.TextField()),
        ),
    ]
